### PR TITLE
Convert README into Markdown instead of Textile

### PR DESCRIPTION
**Pull request by AMR-KELEG**

### CODE REVIEW

**Comment by sushain97** [comment]
I think it's sufficient to symlink `README.md` to `README`.

**Comment by AMR-KELEG** [comment]
@sushain97 Done :smile: 
I prefer using Markdown for documentations.
Do you think we should consider using it for all the repos?
I believe Textile was used by source forge and that's why it's still used in Github after migration.

**Comment by sushain97** [comment]
We do by default: https://github.com/apertium/apertium-init

**Comment by AMR-KELEG** [comment]
> I think it's sufficient to symlink `README.md` to `README`.

I tried adding a symlink to the original file.
I think converting the file using pandoc gets rendered in a better way than just adding a link to the original file.

**Comment by sushain97** [comment]
We have to use a symlink since otherwise other things downstream will break when there's no file called `README`.

**Comment by AMR-KELEG** [comment]
> We have to use a symlink since otherwise other things downstream will break when there's no file called `README`.

I have added a symlink.
I meant that I needed to edit the contents of the original `README` file so that the symlinked `README.md` gets rendered in a better way.

**Comment by sushain97** [comment]
I don't think there's a problem with editing the original file!

**Comment by TinoDidriksen** [comment]
The \\_ are not necessary and indeed break the link. And "1.  make install" is wrong - should use backticks or code wrapping instead.

**Comment by AMR-KELEG** [comment]
@TinoDidriksen I fixed the file.
I have used a script to automate the conversion and inspected the output quickly.
That's why I didn't notice these anomalies.
Thanks for your feedback :smile:

**Pull request merged**
